### PR TITLE
Here are the enhancements....

### LINKED ISSUE #2: Request: Break out HTML, JS, and CSS
It would be a better practice to have the HTML, JS, and CSS be their own files. If someone could setup the project to properly break out these files it would help the project growth stay manageable.

### PR DESCRIPTION
**Pull request by CerealNotFound**
Hello sir,
Here are the enhancements. **_Please thoroughly check it._** I am still a noob and don't know how to use git, the process was a little bit messy but works fine.

### CODE REVIEW

**Review by andrewjrangel — CHANGES_REQUESTED** [review]
It looks like you need to update the href values for the cards in the index.html file, for example line 47 "<a href="AndrewRangelProfilePage.html">"

These are no longer working because AndrewRangelProfilePage.html is no longer in the same directory. I will leave it up to you as a challenge to fix it. You can always open in the index.html in a web browser to test the site. Let me know if you have any questions.

**Comment by CerealNotFound** [comment]
Ok sir, I will do that right away.

**Comment by CerealNotFound** [comment]
Sir I have made the changes, please review it :)

**Comment by andrewjrangel** [comment]
Great work! Congrats on being the first merged PR on the project :)

**Pull request merged**
